# Helm values for CloudWatch MCP Server deployment to Jarvis Demo
# This file can be used for future Helm chart migration

# Application metadata
app:
  name: cloudwatch-mcp
  namespace: jarvis-demo

# Container image configuration
image:
  registry: 897729109735.dkr.ecr.us-east-1.amazonaws.com
  repository: jarvis/cloudwatch_mcp_server
  tag: latest
  pullPolicy: Always

# Replica configuration
replicaCount: 2

# Container configuration
container:
  port: 3334
  protocol: TCP

# Environment variables for IAM Identity Center authentication
env:
  # Authentication
  ENABLE_AUTH: "true"

  # AWS IAM Identity Center configuration
  AWS_IDENTITY_CENTER_REGION: "us-east-1"
  # AWS_IDENTITY_CENTER_ISSUER: ""  # Set via secret or external-secrets
  # AWS_IDENTITY_CENTER_CLIENT_ID: ""  # Set via secret or external-secrets
  # AWS_CLOUDWATCH_ROLE_ARN: ""  # Set via secret or external-secrets

  # CloudWatch configuration
  AWS_REGION: "us-east-1"
  CLOUDWATCH_MCP_SERVER_HOST: "0.0.0.0"
  CLOUDWATCH_MCP_PORT: "3334"

  # Logging
  FASTMCP_LOG_LEVEL: "INFO"

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Service configuration
service:
  type: ClusterIP
  port: 3334
  targetPort: 3334
  protocol: TCP

# Health check probes
livenessProbe:
  httpGet:
    path: /health
    port: 3334
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 3334
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# Node selector (optional)
nodeSelector: {}

# Tolerations (optional)
tolerations: []

# Affinity rules (optional)
affinity: {}

# Service account
serviceAccount:
  create: true
  name: cloudwatch-mcp-sa
  annotations: {}
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/cloudwatch-mcp-role

# External secrets configuration (for IAM Identity Center credentials)
externalSecrets:
  enabled: true
  secretStoreName: jarvis-env
  secretKeys:
    - AWS_IDENTITY_CENTER_ISSUER
    - AWS_IDENTITY_CENTER_CLIENT_ID
    - AWS_CLOUDWATCH_ROLE_ARN

# Ingress configuration (optional)
ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts: []
  tls: []
